version: "3.8"
services:
  webhook:
    build: .
    restart: unless-stopped
    deploy:
      replicas: ${INSTANCE_COUNT}
    ports:
      - "3700-3710:80"
    stdin_open: true 
    tty: true
    environment:
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - smee_data:/config:ro
volumes:
  smee_data:
    external: true
